
package com.fiberhome.mock;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import com.fiberhome.endpoint.ObjectFactory;
import com.fiberhome.endpoint.RequestValue;
import com.fiberhome.endpoint.ResultValue;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "AgentService", targetNamespace = "http://endpoint.fiberhome.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface AgentService {


    /**
     * 
     * @param requestValue
     * @return
     *     returns com.fiberhome.endpoint.ResultValue
     * @throws Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "methodOfTest", targetNamespace = "http://endpoint.fiberhome.com/", className = "com.fiberhome.endpoint.MethodOfTest")
    @ResponseWrapper(localName = "methodOfTestResponse", targetNamespace = "http://endpoint.fiberhome.com/", className = "com.fiberhome.endpoint.MethodOfTestResponse")
    @Action(input = "http://endpoint.fiberhome.com/AgentService/methodOfTestRequest", output = "http://endpoint.fiberhome.com/AgentService/methodOfTestResponse", fault = {
        @FaultAction(className = Exception.class, value = "http://endpoint.fiberhome.com/AgentService/methodOfTest/Fault/Exception")
    })
    public ResultValue methodOfTest(
        @WebParam(name = "requestValue", targetNamespace = "")
        RequestValue requestValue)
        throws Exception
    ;

}
